import OpenAI from 'openai';

export type AIProvider = 'openai' | 'together' | 'anthropic' | 'mock';

interface GenerateTextOptions {
    systemPrompt?: string;
    userPrompt: string;
    temperature?: number;
    maxTokens?: number;
    jsonMode?: boolean;
}

const AI_PROVIDER = (process.env.AI_PROVIDER || 'openai') as AIProvider;
const AI_MODEL = process.env.AI_MODEL || 'gpt-4o';
const IS_RESPONSES_MODEL = AI_MODEL === 'gpt-5.2-pro';

let openaiClient: OpenAI | null = null;
if (AI_PROVIDER === 'openai') {
    if (!process.env.OPENAI_API_KEY) {
        console.warn('Missing OPENAI_API_KEY for openai provider');
    } else {
        openaiClient = new OpenAI({
            apiKey: process.env.OPENAI_API_KEY,
        });
    }
}

export async function generateText(options: GenerateTextOptions): Promise<string> {
    const { systemPrompt, userPrompt, temperature = 0.7, maxTokens = 4000, jsonMode = false } = options;

    if (AI_PROVIDER === 'openai' && openaiClient) {
        try {
            const messages: OpenAI.Chat.Completions.ChatCompletionMessageParam[] = [];
            if (systemPrompt) {
                messages.push({ role: 'system', content: systemPrompt });
            }
            messages.push({ role: 'user', content: userPrompt });

            if (IS_RESPONSES_MODEL) {
                // @ts-ignore - responses API might not be in the typed definition yet depending on version
                const response = await openaiClient.responses.create({
                    model: AI_MODEL,
                    input: userPrompt, // Responses API uses 'input' string, not messages array for simple tasks
                });
                return response.output_text || '';
            }

            const response = await openaiClient.chat.completions.create({
                model: AI_MODEL,
                messages,
                temperature,
                // @ts-ignore - max_completion_tokens is required for newer models (o1/o3)
                max_completion_tokens: maxTokens,
                response_format: jsonMode ? { type: 'json_object' } : undefined,
            });

            return response.choices[0]?.message?.content || '';
        } catch (error) {
            console.error('OpenAI API Error:', error);
            throw new Error('Failed to generate text using OpenAI provider');
        }
    } else if (AI_PROVIDER === 'together') {
        // TODO: Implement Together AI support
        throw new Error('Together AI provider not yet implemented');
    } else if (AI_PROVIDER === 'mock') {
        // Mock Response for testing without API usage
        console.log('Generating MOCK response...');
        await new Promise(resolve => setTimeout(resolve, 2000)); // Simulate delay

        if (jsonMode) {
            return JSON.stringify({
                patient_name: "John Doe",
                dob: "01/01/1980",
                member_id: "XYZ123456789",
                group_id: "GRP-999",
                provider_name: "Dr. Smith",
                provider_npi: "1234567890",
                provider_tin: "12-3456789",
                diagnosis_code: "M54.5",
                procedure_code: "72148",
                clinical_reasoning: "Patient has failed conservative therapy for 6 weeks including NSAIDs and PT. MRI requested to rule out HNP."
            });
        }

        return `# [MOCK] Medical Authorization Request

**Date:** ${new Date().toLocaleDateString()}
**To:** Medical Review Department

**Re:** Letter of Medical Necessity

**Patient Summary:**
Based on the provided clinical notes, the patient fits the criteria for the requested procedure. The patient has a history of chronic pain and has failed conservative therapies including PT and NSAIDs.

**Medical Rationale:**
The requested service (CPT 62323 - Epidural Injection) is medically indicated. The MRI findings show disc herniation at L4-L5, which correlates with the patient's radicular symptoms.

**Conclusion:**
Please approve this request as it meets all standard care guidelines.

*Generated by ARM Mock Mode*`;
    } else if (AI_PROVIDER === 'anthropic') {
        // TODO: Implement Anthropic support
        throw new Error('Anthropic provider not yet implemented');
    } else {
        throw new Error(`Unsupported or unconfigured AI provider: ${AI_PROVIDER}`);
    }
}
