
// Scripts/crawl_aetna.ts
// PURPOSE: Crawl Aetna's public CPB index and generate a SQL seed file with ALL policies.

import fs from 'fs';
import * as cheerio from 'cheerio'; // We'll need to install this or use regex if unavailable

// Aetna CPB Index URLs (They split them by range)
const INDEX_URLS = [
    "https://www.aetna.com/health-care-professionals/clinical-policy-bulletins/medical-clinical-policy-bulletins-0001-0099.html",
    "https://www.aetna.com/health-care-professionals/clinical-policy-bulletins/medical-clinical-policy-bulletins-0100-0199.html",
    "https://www.aetna.com/health-care-professionals/clinical-policy-bulletins/medical-clinical-policy-bulletins-0200-0299.html",
    "https://www.aetna.com/health-care-professionals/clinical-policy-bulletins/medical-clinical-policy-bulletins-0300-0399.html",
    "https://www.aetna.com/health-care-professionals/clinical-policy-bulletins/medical-clinical-policy-bulletins-0400-0499.html",
    "https://www.aetna.com/health-care-professionals/clinical-policy-bulletins/medical-clinical-policy-bulletins-0500-0599.html",
    "https://www.aetna.com/health-care-professionals/clinical-policy-bulletins/medical-clinical-policy-bulletins-0600-0699.html",
    "https://www.aetna.com/health-care-professionals/clinical-policy-bulletins/medical-clinical-policy-bulletins-0700-0799.html",
    "https://www.aetna.com/health-care-professionals/clinical-policy-bulletins/medical-clinical-policy-bulletins-0800-0899.html",
    "https://www.aetna.com/health-care-professionals/clinical-policy-bulletins/medical-clinical-policy-bulletins-0900-0999.html"
];

const OUTPUT_FILE = './supabase/seed_aetna_all.sql';

async function crawl() {
    console.log("🚀 Starting Aetna Mass Crawler...");
    const policies = [];

    // Crawl each index page
    for (const url of INDEX_URLS) {
        console.log(`Analyzing Index: ${url}`);
        try {
            const res = await fetch(url);
            const html = await res.text();

            // Extract Links using Regex (Simpler than installing Cheerio for this env)
            // Pattern: <a href=".../0236.html">0236: MRI Spine</a>
            const linkRegex = /<a href="([^"]+\/(\d{4})\.html)">(\d{4}):?\s*([^<]+)<\/a>/g;
            let match;

            while ((match = linkRegex.exec(html)) !== null) {
                const relativeLink = match[1];
                const cpbNumber = match[2]; // e.g., 0236
                const title = match[4].trim(); // e.g., MRI of the Spine

                // Construct absolute URL
                const absoluteUrl = relativeLink.startsWith('http')
                    ? relativeLink
                    : `https://www.aetna.com${relativeLink}`;

                policies.push({
                    payer: 'Aetna',
                    cpt_code: `CPB-${cpbNumber}`, // Use CPB ID as code for now
                    title: `[CPB ${cpbNumber}] ${title}`,
                    source_url: absoluteUrl
                });
            }

        } catch (e: any) {
            console.error(`Failed to crawl ${url}: ${e.message}`);
        }
    }

    console.log(`✅ Found ${policies.length} Policies.`);

    // Generate SQL
    console.log("💾 Generating SQL...");
    let sql = `-- AUTO-GENERATED BY scripts/crawl_aetna.ts\n`;
    sql += `insert into policies (payer, cpt_code, title, source_url)\nvalues\n`;

    const values = policies.map(p => {
        // Escape single quotes in title
        const safeTitle = p.title.replace(/'/g, "''");
        return `('Aetna', '${p.cpt_code}', '${safeTitle}', '${p.source_url}')`;
    });

    sql += values.join(',\n');
    sql += `\non conflict (payer, cpt_code, organization_id) do update set source_url = excluded.source_url;\n`;

    fs.writeFileSync(OUTPUT_FILE, sql);
    console.log(`🎉 Done! Saved to ${OUTPUT_FILE}`);
}

// Make fetch available globally
(global as any).fetch = fetch;
crawl();
